# Generated by Django 5.1.3 on 2024-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("ecommerce2", "0001_initial"),
        ("ecommerce2", "0002_productmodel_description"),
        ("ecommerce2", "0003_productmodel_short_description"),
        (
            "ecommerce2",
            "0004_productmodel_color_productmodel_product_dimentions_and_more",
        ),
        ("ecommerce2", "0005_remove_productmodel_short_description"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("price", models.FloatField()),
                ("description", models.TextField(null=True)),
                ("color", models.TextField(null=True)),
                ("product_dimentions", models.TextField(null=True)),
                ("seller", models.TextField(null=True)),
            ],
        ),
    ]
