# Generated by Django 5.1.3 on 2024-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce2", "0007_alter_productmodel_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="product_dimentions",
            new_name="product_dimensions",
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("PU", "PUBLICADO"),
                    ("BR", "BORRADOR"),
                    ("PR", "PRIVADO"),
                ],
                default="BR",
                max_length=2,
            ),
        ),
    ]
