# Generated by Django 5.1.3 on 2024-11-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce2", "0009_alter_productmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-updated", "-timestamp"]},
        ),
        migrations.RenameField(
            model_name="productmodel",
            old_name="update",
            new_name="updated",
        ),
    ]
