# Generated by Django 5.1.3 on 2024-11-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce2", "0010_alter_productmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
